GET http://localhost:3000/machines

###


GET http://localhost:3000/machines/12

###

POST http://localhost:3000/machines

{
    "name": "Bicep Curl",
    "machineToGym": "Campus Rec"
}

###

PATCH http://localhost:3000/machines/12
Content-Type: machine.js
{
    "name": "Squat pull"
}

###

DELETE http://localhost:3000/machines/12 
